DROP TABLE IF EXISTS inscricoes CASCADE;
DROP TABLE IF EXISTS curso_tags CASCADE;
DROP TABLE IF EXISTS cursos_tags CASCADE;
DROP TABLE IF EXISTS cursos CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS areas CASCADE;
