services:
  - type: web
    name: ki-springboot
    runtime: docker
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres.znhwbzcqoffspfbbpxor
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: ADMIN_EMAIL
        value: admin@gmail.com
      - key: ADMIN_PASSWORD
        value: admin123
      - key: JAVA_TOOL_OPTIONS
        value: -XX:MaxRAMPercentage=70 -XX:+UseSerialGC
      - key: DB_POOL_MAX
        value: "5"
      - key: DB_POOL_MIN
        value: "1"
